# Generated by Django 4.2.3 on 2023-07-20 02:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aprendiz',
            fields=[
                ('documento_aprendiz', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo_documento', models.CharField(max_length=20)),
                ('nombres_aprendiz', models.CharField(max_length=45)),
                ('apellidos_aprendiz', models.CharField(max_length=45)),
                ('email_personal_aprendiz', models.CharField(max_length=45)),
                ('email_institucional_aprendiz', models.CharField(max_length=45)),
                ('numero_celular', models.IntegerField()),
                ('genero_aprendiz', models.CharField(max_length=1)),
            ],
            options={
                'verbose_name': 'Aprendiz',
                'verbose_name_plural': 'Aprendices',
            },
        ),
        migrations.CreateModel(
            name='Coodinacion',
            fields=[
                ('id_coordinacion', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('nombre_coordinacion', models.CharField(choices=[('Teleinformatica', 'Teleinformatica')], max_length=45)),
            ],
            options={
                'verbose_name': 'Coodinacion',
                'verbose_name_plural': 'Coordinaciones',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('user_type', models.CharField(choices=[('Aprendiz', 'Aprendiz'), ('Instructor', 'Instructor'), ('Coordinacion', 'Coordinación'), ('Bienestar', 'Bienestar')], max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='customuser_set', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='customuser_set', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_entrada', models.TimeField()),
                ('hora_salida', models.TimeField()),
                ('salon', models.IntegerField()),
                ('jornada', models.CharField(choices=[('Manana', 'Mañana'), ('Tarde', 'Tarde'), ('Noche', 'Noche')], max_length=10)),
                ('asignatura', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
            },
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id_programa', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_programa', models.CharField(choices=[('ADSO', 'ADSO')], max_length=45)),
                ('coordinacion_programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asistencia.coodinacion')),
            ],
            options={
                'verbose_name': 'Programa',
                'verbose_name_plural': 'Programas',
            },
        ),
        migrations.CreateModel(
            name='Novedad',
            fields=[
                ('id_novedad', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_novedad', models.CharField(choices=[('Calamidad', 'Calamidad domestica'), ('Medica', 'Novedad medica')], max_length=10)),
                ('observaciones', models.TextField(max_length=300)),
                ('archivo_adjunto', models.FileField(upload_to='pdfs/')),
                ('estado_novedad', models.BooleanField(choices=[(True, 'Aceptada'), (False, 'No aceptada')], default=False)),
                ('aprendiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asistencia.aprendiz')),
            ],
            options={
                'verbose_name': 'Novedad',
                'verbose_name_plural': 'Novedades',
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('documento', models.IntegerField(primary_key=True, serialize=False)),
                ('nombres_intructor', models.CharField(max_length=45)),
                ('apellidos_instructor', models.CharField(max_length=45)),
                ('email_institucional', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='asistencia.customuser')),
            ],
            options={
                'verbose_name': 'Instructor',
                'verbose_name_plural': 'Instructores',
            },
        ),
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id_ficha', models.IntegerField(primary_key=True, serialize=False)),
                ('nivel_formacion', models.CharField(max_length=20)),
                ('horario_ficha', models.ManyToManyField(to='asistencia.horario')),
                ('instructor_ficha', models.ManyToManyField(to='asistencia.instructor')),
                ('programa_ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asistencia.programa')),
            ],
            options={
                'verbose_name': 'Ficha',
                'verbose_name_plural': 'Fichas',
            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado_asistencia', models.CharField(choices=[('Asiste', 'Asiste'), ('Falla', 'Falla'), ('Novedad', 'Novedad')], max_length=10)),
                ('aprendiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asistencia.aprendiz')),
                ('novedad', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asistencia.novedad')),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
            },
        ),
        migrations.AddField(
            model_name='aprendiz',
            name='ficha_aprendiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asistencia.ficha'),
        ),
        migrations.AddField(
            model_name='aprendiz',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='asistencia.customuser'),
        ),
    ]
