# Generated by Django 4.2.3 on 2023-07-19 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ficha',
            name='instructor_ficha',
        ),
        migrations.AddField(
            model_name='ficha',
            name='instructor_ficha',
            field=models.ManyToManyField(to='asistencia.instructor'),
        ),
    ]
