# Generated by Django 4.2.3 on 2023-07-20 04:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0002_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aprendiz',
            name='numero_celular',
            field=models.IntegerField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Este campo debe tener exactamente 10 dígitos.')]),
        ),
        migrations.AlterField(
            model_name='aprendiz',
            name='tipo_documento',
            field=models.CharField(choices=[('Cedula', 'Cedula de ciudadania'), ('Tarjeta', 'Tarjeta de identidad')], max_length=20),
        ),
    ]
