# Generated by Django 4.2.3 on 2023-07-20 04:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0003_alter_aprendiz_numero_celular_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aprendiz',
            name='numero_celular',
            field=models.IntegerField(validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Este campo debe tener exactamente 10 dígitos.')]),
        ),
    ]
