# Generated by Django 4.2.3 on 2023-07-21 01:13

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0004_alter_aprendiz_numero_celular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novedad',
            name='observaciones',
            field=ckeditor.fields.RichTextField(max_length=300),
        ),
    ]
