# Generated by Django 4.2.3 on 2023-07-21 01:29

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0005_alter_novedad_observaciones'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aprendiz',
            options={'ordering': ('-nombres_aprendiz',), 'verbose_name': 'Aprendiz', 'verbose_name_plural': 'Aprendices'},
        ),
        migrations.AlterField(
            model_name='novedad',
            name='observaciones',
            field=ckeditor.fields.RichTextField(default='', max_length=30),
        ),
    ]
