# Generated by Django 4.2.3 on 2023-07-21 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0006_alter_aprendiz_options_alter_novedad_observaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aprendiz',
            name='genero_aprendiz',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('H', 'Homosexual'), ('B', 'Bisexsual'), ('T', 'Transexual')], max_length=1),
        ),
    ]
