# Generated by Django 4.2.3 on 2023-07-21 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0007_alter_aprendiz_genero_aprendiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aprendiz',
            name='genero_aprendiz',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Homosexual', 'Homosexual'), ('Bisexsual', 'Bisexsual'), ('Transexual', 'Transexual')], max_length=10),
        ),
    ]
