# Generated by Django 4.2.3 on 2023-07-21 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0008_alter_aprendiz_genero_aprendiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aprendiz',
            name='numero_celular',
            field=models.IntegerField(),
        ),
    ]
