# Generated by Django 4.2.3 on 2023-07-21 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0009_alter_aprendiz_numero_celular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='jornada',
            field=models.CharField(choices=[('Diurna', 'Diurna'), ('Tarde', 'Tarde'), ('Nocturna', 'Nocturna')], max_length=10),
        ),
    ]
